config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    resources :btcinvoices, shallow: true do
      resources :bitcoin_addrs
    end
  end
  root 'users#index'

end

app/models/btcinvoice.rb
class Btcinvoice < ActiveRecord::Base
  has_many :bitcoin_addrs
  has_one :user
  has_one :issuer, class_name: 'User'
end

app/controllers/btcinvoices_controller.rb
class BtcinvoicesController < ApplicationController
  before_action :set_user, only: [:index, :new, :create]

  # GET /invoices
  # GET /invoices.json
  def index
    @btcinvoices = @user.btcinvoices.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @btcinvoice = Btcinvoice.find(params[:id])
  end

  # GET /invoices/new
  def new
    @btcinvoice = @user.btcinvoices.new
  end

  # GET /invoices/1/edit
  def edit
    @btcinvoice = Btcinvoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @btcinvoice = @user.btcinvoices.new(btcinvoice_params)

    respond_to do |format|
      if @btcinvoice.save
        format.html { redirect_to user_btcinvoices_path(@user, @btcinvoice),
                      notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created,
                      location: user_btcinvoices_path(@user, @btcinvoice) }
      else
        format.html { render :new }
        format.json { render json: @btcinvoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    @btcinvoice = @user.btcinvoices.find(params[:id])
    respond_to do |format|
      if @btcinvoice.update(btcinvoice_params)
        format.html { redirect_to([@user, @btcinvoice],
                                  notice: 'Invoice was successfully updated.') }
        format.json { render :show, status: :ok, location: @btcinvoice }
      else
        format.html { render :edit }
        format.json { render json: @btcinvoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @btcinvoice = @user.btcinvoices.find(params[:id])
    @btcinvoice.destroy
    respond_to do |format|
      format.html { redirect_to user_btcinvoices_url(@user),
                    notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def btcinvoice_params
      params.require(:btcinvoice).permit(:rate, :time_sent, :is_paid, :fiat_amt, :user_id, :issuer_id)
    end
end

app/helpers/btcinvoices_helper.rb
module BtcinvoicesHelper
end

app/views/btcinvoices/_form.html.erb
<%= form_for([@user, @btcinvoice]) do |f| %>
  <% if @btcinvoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@btcinvoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @btcinvoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :time_sent %><br>
    <%= f.datetime_select :time_sent %>
  </div>
  <div class="field">
    <%= f.label :is_paid %><br>
    <%= f.check_box :is_paid %>
  </div>
  <div class="field">
    <%= f.label :fiat_amt %><br>
    <%= f.text_field :fiat_amt %>
  </div>
  <div class="field">
    <%= f.label :issuer_id %><br>
    <%= f.collection_select(:issuer_id, User.all, :id, :full_name) %>
  </div>
  <div class="field">
    <%= f.label(:user_id, "Recipient") %><br>
    <%= f.collection_select(:user_id, User.all, :id, :full_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/btcinvoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', user_btcinvoice_path(@user, params[:id]) %> |
<%= link_to 'Back', user_btcinvoices_path(@user) %>

app/views/btcinvoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Rate</th>
      <th>Time sent</th>
      <th>Is paid</th>
      <th>Fiat amt</th>
      <th>Recipient</th>
      <th>Issuer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.btcinvoices.each do |invoice| %>
      <tr>
        <td><%= invoice.rate %></td>
        <td><%= invoice.time_sent %></td>
        <td><%= invoice.is_paid %></td>
        <td><%= invoice.fiat_amt %></td>
        <td><%= User.find(invoice.user_id).full_name if invoice.user_id %></td>
        <td><%= User.find(invoice.issuer_id).full_name if invoice.issuer_id %></td>
        <td><%= link_to 'Show', btcinvoice_path(invoice) %></td>
        <td><%= link_to 'Edit', edit_btcinvoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', btcinvoice_path(invoice), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_user_btcinvoice_path(@user) %>

app/views/btcinvoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', user_btcinvoices_path %>

app/views/btcinvoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate:</strong>
  <%= @btcinvoice.rate %>
</p>

<p>
  <strong>Time sent:</strong>
  <%= @btcinvoice.time_sent %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @btcinvoice.is_paid %>
</p>

<p>
  <strong>Fiat amt:</strong>
  <%= @btcinvoice.fiat_amt %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= User.find(@btcinvoice.user_id).full_name if @btcinvoice.user_id %>
</p>

<p>
  <strong>Issuer:</strong>
  <%= User.find(@btcinvoice.issuer_id).full_name if @btcinvoice.issuer_id %>
</p>

<p>
  <strong><%= link_to 'Bitcoin Addresses', btcinvoice_bitcoin_addrs_path(@btcinvoice) %></strong>
</p>

<%= link_to 'Edit', edit_btcinvoice_path(@btcinvoice) %>