config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    resources :btcinvoices, shallow: true do
      resources :bitcoin_addrs
    end
  end
  root 'users#index'

end

app/models/bitcoin_addr.rb
class BitcoinAddr < ActiveRecord::Base
  belongs_to :btcinvoice
end

app/controllers/bitcoin_addrs_controller.rb
class BitcoinAddrsController < ApplicationController
  before_action :set_btcinvoice, only: [:index, :new, :create]

  # GET /bitcoin_addrs
  # GET /bitcoin_addrs.json
  def index
    @bitcoin_addrs = @btcinvoice.bitcoin_addrs
  end

  # GET /bitcoin_addrs/1
  # GET /bitcoin_addrs/1.json
  def show
    @bitcoin_addr = BitcoinAddr.find(params[:id])
  end

  # GET /bitcoin_addrs/new
  def new
    @bitcoin_addr = BitcoinAddr.new
  end

  # GET /bitcoin_addrs/1/edit
  def edit
  end

  # POST /bitcoin_addrs
  # POST /bitcoin_addrs.json
  def create
    @bitcoin_addr = BitcoinAddr.new(bitcoin_addr_params)

    respond_to do |format|
      if @bitcoin_addr.save
        format.html { redirect_to @bitcoin_addr, notice: 'Bitcoin addr was successfully created.' }
        format.json { render :show, status: :created, location: @bitcoin_addr }
      else
        format.html { render :new }
        format.json { render json: @bitcoin_addr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bitcoin_addrs/1
  # PATCH/PUT /bitcoin_addrs/1.json
  def update
    respond_to do |format|
      if @bitcoin_addr.update(bitcoin_addr_params)
        format.html { redirect_to @bitcoin_addr, notice: 'Bitcoin addr was successfully updated.' }
        format.json { render :show, status: :ok, location: @bitcoin_addr }
      else
        format.html { render :edit }
        format.json { render json: @bitcoin_addr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bitcoin_addrs/1
  # DELETE /bitcoin_addrs/1.json
  def destroy
    @bitcoin_addr.destroy
    respond_to do |format|
      format.html { redirect_to bitcoin_addrs_url, notice: 'Bitcoin addr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_btcinvoice
      @btcinvoice = Btcinvoice.find(params[:btcinvoice_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bitcoin_addr_params
      params.require(:bitcoin_addr).permit(:address, :btcinvoice_id, :is_used)
    end
end

app/helpers/bitcoin_addrs_helper.rb
module BitcoinAddrsHelper
end

app/views/bitcoin_addrs/_form.html.erb
<%= form_for([@btcinvoice, @bitcoin_addr]) do |f| %>
  <% if @bitcoin_addr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bitcoin_addr.errors.count, "error") %> prohibited this bitcoin_addr from being saved:</h2>

      <ul>
      <% @bitcoin_addr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :btcinvoice_id %><br>
    <%= f.number_field :btcinvoice_id %>
  </div>
  <div class="field">
    <%= f.label :is_used %><br>
    <%= f.check_box :is_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bitcoin_addrs/edit.html.erb
<h1>Editing Bitcoin Addr</h1>

<%= render 'form' %>

<%= link_to 'Show', @bitcoin_addr %> |
<%= link_to 'Back', bitcoin_addrs_path %>

app/views/bitcoin_addrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bitcoin Addrs</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Invoice</th>
      <th>Is used</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bitcoin_addrs.each do |bitcoin_addr| %>
      <tr>
        <td><%= bitcoin_addr.address %></td>
        <td><%= bitcoin_addr.btcinvoice_id %></td>
        <td><%= bitcoin_addr.is_used %></td>
        <td><%= link_to 'Show', bitcoin_addr %></td>
        <td><%= link_to 'Edit', edit_bitcoin_addr_path(bitcoin_addr) %></td>
        <td><%= link_to 'Destroy', bitcoin_addr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bitcoin addr', new_btcinvoice_bitcoin_addr_path(@btcinvoice) %>

app/views/bitcoin_addrs/new.html.erb
<h1>New Bitcoin Addr</h1>

<%= render 'form' %>

app/views/bitcoin_addrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @bitcoin_addr.address %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @bitcoin_addr.btcinvoice_id %>
</p>

<p>
  <strong>Is used:</strong>
  <%= @bitcoin_addr.is_used %>
</p>

<%= link_to 'Edit', edit_bitcoin_addr_path(@bitcoin_addr) %> |
<%= link_to 'Back', btcinvoice_bitcoin_addrs_path(@bitcoin_addr.btcinvoice_id) %> |